/**
 * @file src/plugins/opencode/aet_handler.ts
 *
 * OpenCode plugin entry — `bin/aet_handler.js` in the built package. This
 * is the port of the Claude Code handler (claude_code/hooks/handlers/
 * aet_handler.ts) to the OpenCode Plugin API: ONE entry registers every
 * hook, mirroring how the CC handler dispatches all events from one file.
 *
 * Bundled by scripts/build.mjs to `dist/plugins/opencode/bin/aet_handler.js`
 * (ESM, zero external deps) and referenced from the package's `package.json`
 * `main` field so OpenCode loads it as a plugin. The `config` hook resolves
 * `skills/` + `commands/` relative to THIS file at runtime, so the plugin
 * package is self-contained wherever it is installed.
 *
 * Registered hooks (claude event → opencode hook, per 新方案.md §2.3):
 *   1. `config`                        — register skills/commands dirs
 *   2. `command.execute.before` (ACTIVE)   — UserPromptSubmit: slash → command-init
 *   3. `tool.execute.before`  (PASSIVE pre)  — PreToolUse: rewrite aet Bash args
 *   4. `tool.execute.after`   (PASSIVE post) — PostToolUse: replace result with prompt
 *   5. `event` (passive)      — session.status observer (stub)
 *   6. `experimental.chat.system.transform` (legacy stub)
 *
 * SessionStart boot mode stays DISABLED (as in the CC handler) — AET entry
 * COMMANDS (/aet-<id>) are generated by `aet plugin init --agent opencode`
 * into the project's `.opencode/commands/`, and the `command.execute.before`
 * hook routes them through `aet workflow command-init`.
 */

import { AET_PLUGIN_ID } from './constants.js';
import { registerConfigHook } from './hooks/config.js';
import { registerCommandBeforeHook } from './hooks/command_before.js';
import { registerToolBeforeHook } from './hooks/tool_before.js';
import { registerToolAfterHook } from './hooks/tool_after.js';
import { registerSessionStatusHook } from './hooks/session_status.js';
import { registerSystemTransformHook } from './hooks/system_transform.js';
import type { Plugin, PluginContext, PluginHooks } from './types.js';

/**
 * OpenCode plugin entry.
 *
 * Per the OpenCode Plugin API: the plugin is an async function that RETURNS
 * its hooks object (the `Hooks` interface) — it does NOT register hooks on
 * the context. Each register* helper below builds one hook handler.
 */
const aetPlugin: Plugin = async (ctx: PluginContext) => {
  const hooks = {
    config: registerConfigHook(ctx),
    'command.execute.before': registerCommandBeforeHook(ctx),
    'tool.execute.before': registerToolBeforeHook(ctx),
    'tool.execute.after': registerToolAfterHook(ctx),
    event: registerSessionStatusHook(ctx),
    'experimental.chat.system.transform': registerSystemTransformHook(ctx),
  } as PluginHooks;

  // Announce plugin presence.
  await ctx.client.app.log({
    body: {
      service: AET_PLUGIN_ID,
      level: 'info',
      message: 'AET plugin loaded — workflow commands intercepted, aet Bash args rewritten, skills/commands registered',
    },
  });

  return hooks;
};

export default aetPlugin;
export { aetPlugin };
